# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{maildir}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Suggs"]
  s.date = %q{2010-01-05}
  s.description = %q{A ruby library for reading and writing arbitrary messages in DJB's maildir format}
  s.email = %q{aaron@ktheory.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "NOTES.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "benchmarks/runner",
     "lib/maildir.rb",
     "lib/maildir/message.rb",
     "lib/maildir/unique_name.rb",
     "maildir.gemspec",
     "test/test_helper.rb",
     "test/test_maildir.rb",
     "test/test_message.rb",
     "test/test_unique_name.rb"
  ]
  s.homepage = %q{http://github.com/ktheory/maildir}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Read & write messages in the maildir format}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_maildir.rb",
     "test/test_message.rb",
     "test/test_unique_name.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

